# Generated by Django 4.2.5 on 2024-01-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_tasks_google_calendar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='google_calendar_id',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
