# Generated by Django 4.2.5 on 2024-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_tasks_google_calendar_id_alter_tasks_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
