# Generated by Django 4.2.5 on 2024-01-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tasks_google_calendar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='google_calendar_id',
        ),
    ]
