# Generated by Django 4.2.5 on 2024-01-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_tasks_google_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
