# Generated by Django 4.2.5 on 2024-01-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_tasks_due_date_alter_tasks_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
