# Generated by Django 4.2.5 on 2023-12-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tasks_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dependency',
            field=models.ManyToManyField(blank=True, to='tasks.tasks'),
        ),
    ]
