# Generated by Django 4.2.5 on 2023-12-31 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
