# Generated by Django 4.2.5 on 2023-12-18 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quckie', '0002_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 19, 7, 39, 23, 742142, tzinfo=datetime.timezone.utc)),
        ),
    ]
